blog/urls.py
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from django.urls import path

from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', cache_page(60)(BlogListView.as_view()), name='blog_list')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import HomePageView, ClientListView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView, \
    MailingListView, MailingCreateView, MailingDetailView, MailingUpdateView, MailingDeleteView, MessageListView, \
    MessageCreateView, MessageUpdateView, MessageDeleteView, LogsListView

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),

    path('my_clients/', ClientListView.as_view(), name='client_list'),
    path('my_clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('my_clients/detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('my_clients/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('my_clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

    path('my_mailing/', MailingListView.as_view(), name='mailing_list'),
    path('my_mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('my_mailing/detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('my_mailing/update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('my_mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),

    path('my_messages/', MessageListView.as_view(), name='message_list'),
    path('my_messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('my_messages/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('my_messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('my_logs/', LogsListView.as_view(), name='logs_list'),
]

mailing/models.py
import datetime

from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """Кто получает рассылку"""
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=200, verbose_name='Фамилия')
    surname = models.CharField(max_length=100, **NULLABLE, verbose_name='Отчество')
    email = models.EmailField(unique=True, verbose_name='Почта')
    comment = models.TextField(**NULLABLE, verbose_name='Комментарий')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.last_name} {self.first_name} ({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('last_name', 'first_name',)


class Message(models.Model):
    """Сообщение рассылки"""
    title = models.CharField(max_length=150, default='Без темы', verbose_name='Тема письма')
    text_body = models.TextField(**NULLABLE, verbose_name='Содержание')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ('title',)


class Mailing(models.Model):
    """Настройки и статусы рассылки"""
    PERIOD_CHOICES = (
        ('once', '1 раз'),
        ('daily', 'Ежедневно'),
        ('weekly', 'Еженедельно'),
        ('monthly', 'Ежемесячно'),
    )

    STATUS_CHOICES = (
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('stopped', 'Завершена'),
    )

    title = models.CharField(max_length=150, verbose_name='Название рассылки')

    date_start = models.DateTimeField(default=datetime.datetime.now, verbose_name='Время начала рассылки')
    date_stop = models.DateTimeField(default=datetime.datetime.now, verbose_name='Время окончания рассылки')
    period = models.CharField(choices=PERIOD_CHOICES, default='once', verbose_name='Периодичность рассылки')
    status = models.CharField(choices=STATUS_CHOICES, default='created', verbose_name='Статус рассылки')

    client = models.ManyToManyField(Client, verbose_name='Получатели')
    message = models.ForeignKey(Message, on_delete=models.PROTECT, verbose_name='Сообщение')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name='Владелец', **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='Активная')

    def __str__(self):
        return f' {self.title} ({self.date_start}-{self.date_stop}, {self.period}, {self.status})'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('status',)
        permissions = [
            ('set_is_active', 'Изменить активность рассылки'),
        ]


class Logs(models.Model):
    """Логи и статусы логов рассылки"""
    LOG_CHOICES = (
        (True, 'Успешно'),
        (False, 'Ошибка'),
    )

    attempt_time = models.DateTimeField(verbose_name='Дата и время последней попытки', **NULLABLE)
    attempt_status = models.CharField(max_length=50, choices=LOG_CHOICES, default=True, verbose_name='Статус попытки')
    server_response = models.CharField(max_length=255, verbose_name='Ответ почтового сервера', **NULLABLE)

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка', **NULLABLE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент рассылки', **NULLABLE)

    def __str__(self):
        return f'Попытка отправки {self.attempt_time}, статус - {self.attempt_status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'
        ordering = ('attempt_status',)

mailing/forms.py
from django import forms
from services import StyleFormMixin

from mailing.models import Client, Mailing, Message


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        fields = '__all__'


class MailingForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        fields = '__all__'


class MessageForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Message
        fields = '__all__'

mailing/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView, TemplateView

from blog.models import Blog
from mailing.forms import ClientForm, MailingForm, MessageForm
from mailing.models import Client, Mailing, Message, Logs


class HomePageView(TemplateView):
    """Отображение домашней страницы"""
    template_name = 'mailing/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailing_count'] = Mailing.objects.all().count()
        context_data['active_mailing_count'] = Mailing.objects.filter(is_active=True,).count()
        context_data['clients_count'] = Client.objects.all().distinct().count()
        context_data['three_posts'] = Blog.objects.all()[:3]

        return context_data


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.object.owner == self.request.user:
            return self.object
        raise Http404


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.object.owner == self.request.user:
            return self.object
        raise Http404


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.object.owner == self.request.user:
            return self.object
        raise Http404


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.object.owner == self.request.user:
            return self.object
        raise Http404


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.object.owner == self.request.user:
            return self.object
        raise Http404


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.object.owner == self.request.user:
            return self.object
        raise Http404


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.object.owner == self.request.user:
            return self.object
        raise Http404


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.object.owner == self.request.user:
            return self.object
        raise Http404


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class LogsListView(LoginRequiredMixin, ListView):
    model = Logs

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        context_data['all'] = context_data['object_list'].count()
        context_data['success'] = context_data['object_list'].filter(attempt_status=True).count()
        context_data['error'] = context_data['object_list'].filter(attempt_status=False).count()
        return context_data


@login_required
def active_toggle(request, pk):
    mailing_item = get_object_or_404(Mailing, pk=pk)
    if mailing_item.is_active:
        mailing_item.is_active = False
    else:
        mailing_item.is_active = True
    mailing_item.save()
    return redirect(reverse('mailing:mailing_list'))

mailing/templates/mailing/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>MassMessage</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
</head>
<body>

<header>
    {% include 'mailing/includes/inc_menu.html' %}
</header>


<main>
{% block content %}
{% endblock %}
</main>

    <!-- FOOTER -->
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-12 mb-12 text-center">
    {% include 'mailing/includes/inc_client_card.html' %}
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <p class="fw-bold text-danger">Хотите удалить клиента "{{ object }}" ?</p>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'mailing:client_list' %}" class="btn btn-success">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{%  extends 'mailing/base.html'%}

{% block content %}
<div class="row row-cols-1 row-cols-md-12 mb-12 text-center">
    {% include 'mailing/includes/inc_client_card.html' %}
            <div class="card-footer">
                <div class="btn-group">
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'mailing:client_update' object.pk %}">Изменить</a>
                    <a class="btn btn-sm btn-outline-danger"
                       href="{% url 'mailing:client_delete' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row text-center">
        <div class="w-50 mx-auto">
            <div class="card">
                <div class="card-body text-dark">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="mx-auto" style="width: 200px;">
    <div class="col-12 mb-5">
        <a class="btn btn-outline-dark" href="{% url 'mailing:client_create' %}">Создать клиента</a>
    </div>
</div>

<div class="row row-cols-1 row-cols-md-6 mb-6 text-center">
    {% for object in object_list %}
    {% include 'mailing/includes/inc_client_card.html' %}
            <div class="card-footer">
                <div class="btn-group">
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'mailing:client_detail' object.pk %}">Открыть</a>
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'mailing:client_update' object.pk %}">Изменить</a>
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'mailing:client_delete' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}

{% block content %}
{% include 'mailing/includes/inc_carousel.html' %}

<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">
    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-header"><h5 class="card-title">Статистика сервиса</h5></div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Количество рассылок</td>
                            <td>{{ mailing_count }}</td>
                        </tr>
                        <tr>
                            <td>Количество активных рассылок</td>
                            <td>{{ active_mailing_count }}</td>
                        </tr>
                        <tr>
                            <td>Количество уникальных клиентов</td>
                            <td>{{ clients_count }}</td>
                    </table>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- START THE FEATURETTES -->
    {% for post in three_posts %}
    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">{{ post.title }}
            </h2>
            <p class="lead">{{ post.content }}</p>
        </div>
        <div class="col-md-5">
            <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500"
                 height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#eee"/>
                <text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text>
            </svg>

        </div>
    </div>
    {% endfor %}
    <!-- /END THE FEATURETTES -->

</div><!-- /.container -->
{% endblock %}

mailing/templates/mailing/logs_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="mx-auto" style="width: 200px;">
    <div class="col-12 mb-5">
        <a class="btn" role="button" data-bs-toggle="button"></a>
    </div>
</div>

<div class="row">
    <div class="col-md-8 mx-auto">
        <div class="card">
            <div class="card-header"><h5 class="card-title">Статистика рассылок</h5></div>
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Количество рассылок</td>
                        <td>{{ all }}</td>
                    </tr>
                    <tr>
                        <td>Количество успешных рассылок</td>
                        <td>{{ success }}</td>
                    </tr>
                    <tr>
                        <td>Количество неудачных рассылок</td>
                        <td>{{ error }}</td>
                </table>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-12 mb-12 text-center">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <p class="fw-bold text-danger">Хотите удалить рассылку "{{ object }}" ?</p>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-success">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{%  extends 'mailing/base.html'%}

{% block content %}
<div class="row row-cols-1 row-cols-md-12 mb-12 text-center">
    <div class="col-4">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Рассылка {{ object.title }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Название: {{ object.title }}</li>
                    <li>Время рассылки: {{ object.date_start }} - {{ object.date_stop }}</li>
                    <li>Периодичность: {{ object.period }}</li>
                    <li>Статус: {{ object.status }}</li>
                    <li>Сообщение: {{ object.message }}</li>
                    <li>Получатели: {{ object.clients }}</li>
                </ul>
            </div>
            <div class="card-footer">
                <div class="btn-group">
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'mailing:mailing_update' object.pk %}">Изменить</a>
                    <a class="btn btn-sm btn-outline-danger" href="{% url 'mailing:mailing_delete' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row text-center">
        <div class="w-50 mx-auto">
            <div class="card">
                <div class="card-body text-dark">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="mx-auto" style="width: 200px;">
    <div class="col-12 mb-5">
        <a class="btn btn-outline-dark" href="{% url 'mailing:mailing_create' %}">Создать рассылку</a>
    </div>
</div>


<div class="row row-cols-1 row-cols-md-6 mb-6 text-center">
    {% for object in object_list %}
    <div class="col-4">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Рассылка {{ object.title }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Название: {{ object.title }}</li>
                    <li>Время рассылки: {{ object.date_start }} - {{ object.date_stop }}</li>
                    <li>Периодичность: {{ object.period }}</li>
                    <li>Статус: {{ object.status }}</li>
                    <li>Сообщение: {{ object.message }}</li>
                    <li>Получатели: {{ object.clients }}</li>
                </ul>
            </div>
            <div class="card-footer">
                <div class="btn-group">
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'mailing:mailing_detail' object.pk %}">Открыть</a>
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'mailing:mailing_update' object.pk %}">Изменить</a>
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'mailing:mailing_delete' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-12 mb-12 text-center">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <p class="fw-bold text-danger">Хотите удалить сообщение "{{ object }}" ?</p>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'mailing:client_list' %}" class="btn btn-success">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row text-center">
        <div class="w-50 mx-auto">
            <div class="card">
                <div class="card-body text-dark">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="mx-auto" style="width: 200px;">
    <div class="col-12 mb-5">
        <a class="btn btn-outline-dark" href="{% url 'mailing:message_create' %}">Создать сообщение</a>
    </div>
</div>


<div class="row row-cols-1 row-cols-md-6 mb-6 text-center">
    {% for object in object_list %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Сообщение {{ object.pk }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Тема: {{ object.title }}</li>
                    <li>Текст: {{ object.text_body }}</li>
                </ul>
            </div>

            <div class="card-footer">
                <div class="btn-group">
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'mailing:message_update' object.pk %}">Изменить</a>
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'mailing:message_delete' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endblock %}