blog/urls.py
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from django.urls import path

from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', cache_page(60)(BlogListView.as_view()), name='blog_list')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, VerifyCodeView, UserUpdateView, get_new_password, UserListView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_code/', VerifyCodeView.as_view(), name='verify_code'),
    path('get_new_password/', get_new_password, name='get_new_password'),
    path('profile_edit/', UserUpdateView.as_view(), name='profile_edit'),
    path('users/', UserListView.as_view(), name='user_list'),
    ]

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models

from mailing.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')

    avatar = models.ImageField(upload_to='users/', **NULLABLE, verbose_name='аватар')
    phone = models.CharField(max_length=35, **NULLABLE, verbose_name='номер телефона')

    verify_code = models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Код верификации')
    is_verified = models.BooleanField(default=False, verbose_name='Верификация')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('block_user', 'Заблокировать пользователя')
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from services import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserAdminForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = '__all__'

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView

from services import send_new_password
from users.forms import UserRegisterForm, UserForm, UserAdminForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:verify_code')
    template_name = 'users/register.html'

    # def get_object(self, queryset=None):
    # """Если пользователь с таким email уже существует"""
    #     email = self.user.email
    #     user = User.objects.filter(email=email).first()
    #     if user:
    #         return redirect('users:login')

    def form_valid(self, form: UserRegisterForm):
        new_user = form.save()
        send_mail(
            subject='Подтверждение регистрации',
            message=f'Код подтверждения {new_user.verify_code}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email],
        )
        return super().form_valid(form)


class VerifyCodeView(View):
    model = User
    template_name = 'users/verify_code.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        verify_code = request.POST.get('verify_code')
        user = User.objects.filter(verify_code=verify_code).first()
        if user:
            user.is_verified = True
            user.save()
            return redirect('users:login')

        return redirect('users:verify_code')


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile_edit')

    def get_form_class(self):
        if self.request.user.is_staff:
            form_class = UserAdminForm
            return form_class
        form_class = UserForm
        return form_class

    def get_object(self, queryset=None):
        """Редактируем текущего пользователя без передачи pk"""
        return self.request.user

    # def get_object(self, pk=None):  HELP!!!
    #     """Если текущий пользователь - персонал, то редактирует выбранного пользователя из списка с передачей пк.
    #     Если не персонал - редактирует свой профиль без передачи пк."""
    #     if self.request.user.is_staff:
    #         user = User.objects.filter(id=pk)
    #         return user
    #
    #     return self.request.user


class UserListView(LoginRequiredMixin, ListView):
    model = User
    form_class = UserAdminForm

    def get_queryset(self):
        if self.request.user.is_staff:
            return User.objects.all()


@login_required
def get_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    request.user.set_password(new_password)
    request.user.save()
    send_new_password(request.user.email, new_password)
    return redirect(reverse('users:login'))

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-12 mb-12 text-center">
    <div class="col-3"></div>
    <div class="col-12">
        <div class="card">
            <div class="card-header text-dark"></div>
            <div class="card-body text-dark">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-dark">Войти</button>
                </form>
            </div>
            <div class="card-footer text-dark"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-12 mb-12 text-center">
    <div class="col-3"></div>
    <div class="col-12">
        <div class="card">
            <div class="card-header text-dark"></div>
            <div class="card-body text-dark">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-dark">Зарегистрироваться</button>
                </form>
            </div>
            <div class="card-footer text-dark"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Мой профиль
            </div>
            <div class="card-body">
                <form method="post" >
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:get_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
                <p> Новый пароль будет отправлен на почту {{ user.email }} </p>
            </div>

        </div>
    </div>
</div>


{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="row row-cols-1 row-cols-md-6 mb-6 text-center">
    {% for object in object_list %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Пользователь {{ object.pk }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Почта: {{ object.email }}</li>
                    <li>Активность: {{ object.is_active }}</li>
                </ul>
            </div>

            <div class="card-footer">
                <div class="btn-group">
                    <a class="btn btn-sm btn-outline-dark" href="{% url 'users:profile_edit' %}">Изменить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endblock %}

users/templates/users/verify_code.html
{% extends 'mailing/base.html' %}

{%block content%}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header text-dark">
                    <h3 class="card-title">
                        Введите код подтверждения
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="text" name="verify_code" class="form-control" id="name" placeholder="Введите код" required>
                    <button type="submit" class="btn btn-primary">Подтвердить</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}